# Reference:
#   - https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check early in the week - downstream dependabot checks (e.g. Iris) run deliberately later in the week.
      #  Therefore allowing time for this update to be merged-and-released first.
      interval: "weekly"
      day: "monday"
      time: "01:00"
      timezone: "Europe/London"
    labels:
      - "🤖 bot"
