# Reference:
#   - https://github.com/actions/checkout
#   - https://github.com/mgedmin/check-manifest

name: ci-manifest

on:
  workflow_call:

jobs:
  manifest:
    name: "check-manifest"

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "check-manifest"
        run: |
          pipx run check-manifest
