# Reference:
#   - https://github.com/actions/checkout
#   - https://github.com/mgedmin/check-manifest

name: ci-manifest

on:
  workflow_call:

jobs:
  manifest:
    name: "check-manifest"

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: "check-manifest"
        run: |
          pipx run check-manifest
