name: ci-release

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    if: "github.repository_owner == 'SciTools'"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    env:
      WF_VERSION_FNAME: "version.txt"

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: true

      - name: "calculate release version"
        run: |
          git pull
          if [ -f "${WF_VERSION_FNAME}" ]
          then
            WF_VERSION=$(cat ${WF_VERSION_FNAME})
            WF_DATE=$(echo ${WF_VERSION} | cut -d. -f1-2)
            WF_SERIAL=$(echo ${WF_VERSION} | cut -d. -f3)
            NOW_DATE=$(date +%Y.%m)
            NOW_SERIAL=0
            if [ "${WF_DATE}" == "${NOW_DATE}" ]
            then
              NOW_SERIAL=$(expr ${WF_SERIAL} + 1)
            fi
            WF_VERSION="${NOW_DATE}.${NOW_SERIAL}"
          else
            WF_VERSION="$(date +%Y.%m).0"
            echo "WF_BOOTSTRAP=1" >> ${GITHUB_ENV}
          fi
          echo "WF_VERSION=${WF_VERSION}" >> ${GITHUB_ENV}

      - name: "store release version"
        env:
          WF_VERSION: ${{ env.WF_VERSION }}
        run: |
          echo ${WF_VERSION} > ${WF_VERSION_FNAME}
          if [ -n "${WF_BOOTSTRAP}" ]
          then
            git add ${WF_VERSION_FNAME}
          fi
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git commit -am "Automated release for version \"${WF_VERSION}\""
          git push

      - name: "perform release"
        env:
          WF_VERSION: ${{ env.WF_VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${WF_VERSION} --generate-notes

