# This workflow periodically creates new environment lock files based on the newest
# available packages and dependencies.
#
# Environment specifications are given as conda environment.yml files found in
# `requirements/py**.yml`.  These state the packages required, the conda channels
# that the packages will be pulled from, and any versions of packages that need to be
# pinned at specific versions.
#
# For environments that have changed, a pull request will be made and submitted
# to the main branch

name: Refresh Lockfiles


on:
  workflow_call:
    secrets:
      AUTH_APP_ID:
        required: true
      AUTH_APP_PRIVATE_KEY:
        required: true

permissions: {}

jobs:
  get_python_matrix:
    # Determines which Python versions should be included in the matrix used in
    # the gen_lockfiles job.
    if: "github.repository_owner == 'SciTools' || github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_py.outputs.matrix }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - id: get_py
        run: echo "MATRIX=$(ls -1 requirements/py*.yml | xargs -n1 basename | sed 's/....$//' | jq -cnR '[inputs]')" >> ${GITHUB_OUTPUT}

  gen_lockfiles:
    # This is a matrix job: it splits to create new lockfiles for each
    # of the CI test python versions.
    if: "github.repository_owner == 'SciTools' || github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-latest
    needs: get_python_matrix

    strategy:
      matrix:
        python: ${{ fromJSON(needs.get_python_matrix.outputs.MATRIX) }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: install requirements
        run: |
          source $CONDA/bin/activate base
          conda update -n base --all

      - name: generate lockfile
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: |
          pipx run conda-lock -k explicit -p linux-64 -f requirements/${MATRIX_PYTHON}.yml
          mv conda-linux-64.lock ${MATRIX_PYTHON}-linux-64.lock

      - name: output lockfile
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: lock-artifacts-${{matrix.python}}
          path: ${{matrix.python}}-linux-64.lock

  create_pr:
    # Once the matrix job has completed all the lock files will have been
    # uploaded as artifacts.
    # Download the artifacts, add them to the repo, and create a PR.
    if: "github.repository_owner == 'SciTools' || github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-latest
    needs: gen_lockfiles

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: get artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          path: ${{ github.workspace }}/requirements/locks
          merge-multiple: true

      - name: "Generate token"
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        id: generate-token
        with:
          client-id: ${{ secrets.AUTH_APP_ID }}
          private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Updated environment lockfiles
          committer: "Lockfile bot <noreply@github.com>"
          author: "Lockfile bot <noreply@github.com>"
          delete-branch: true
          branch: auto-update-lockfiles
          title: "[CI Bot] environment lockfiles auto-update"
          body: |
            Lockfiles updated to the latest resolvable environment.
            ### If the CI tasks fail, create a new branch based on this PR and add the required fixes to that branch.
          labels: |
            New: Pull Request
            Bot

      - name: Check Pull Request
        if: steps.cpr.outputs.pull-request-number != ''
        env:
          CPR_PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }} 
          CPR_PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          CPR_PR_OPERATION: ${{ steps.cpr.outputs.pull-request-operation }}
          CPR_PR_HEAD_SHA: ${{ steps.cpr.outputs.pull-request-head-sha }} 
        run: |
          echo "### :rocket: Pull-Request Summary" >> ${GITHUB_STEP_SUMMARY}
          echo "" >> ${GITHUB_STEP_SUMMARY}
          echo "The following lock-files pull-request has been auto-generated:"
          echo "- **PR** #${CPR_PR_NUMBER}" >> ${GITHUB_STEP_SUMMARY}
          echo "- **URL** ${CPR_PR_URL}" >> ${GITHUB_STEP_SUMMARY}
          echo "- **Operation** [${CPR_PR_OPERATION}]" >> ${GITHUB_STEP_SUMMARY}
          echo "- **SHA** ${CPR_PR_HEAD_SHA}" >> ${GITHUB_STEP_SUMMARY}
